from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER


def generate_pdf_report(
    file_path,
    history_data
):

    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    heading_style = styles["Heading2"]
    normal_style = styles["Normal"]

    elements = []

    # ==========================================
    # Title
    # ==========================================

    elements.append(
        Paragraph(
            "Multi-Agent Negotiation Simulator",
            title_style
        )
    )

    elements.append(
        Spacer(1, 10)
    )

    elements.append(
        Paragraph(
            "Negotiation Analytics Report",
            heading_style
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    # ==========================================
    # Overall Statistics
    # ==========================================

    total = len(history_data)

    agreements = sum(
        1
        for item in history_data
        if item.get("status") == "agreement_reached"
    )

    deadlocks = sum(
        1
        for item in history_data
        if item.get("status") == "deadlock"
    )

    success_rate = (
        (agreements / total) * 100
        if total > 0
        else 0
    )
    average_score = (
        sum(
            item.get("negotiation_score", 0)
            for item in history_data
        ) / total
        if total > 0
        else 0
    )

    elements.append(
        Paragraph(
            "Overall Performance",
            heading_style
        )
    )

    elements.append(
        Spacer(1, 8)
    )

    max_rounds = sum(
        1
        for item in history_data
        if item.get("status") == "max_rounds_reached"
    )

    performance_data = [
        ["Metric", "Value"],
        ["Total Negotiations", str(total)],
        ["Agreements", str(agreements)],
        ["Deadlocks", str(deadlocks)],
        ["Max Rounds", str(max_rounds)],
        ["Success Rate", f"{success_rate:.1f}%"],
        ["Average Negotiation Score", f"{average_score:.1f}/100"]
    ]

    performance_table = Table(
        performance_data,
        colWidths=[250, 150]
    )

    performance_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ALIGN", (1, 1), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ])
    )

    elements.append(
        performance_table
    )

    elements.append(
        Spacer(1, 25)
    )

    # ==========================================
    # Negotiation History
    # ==========================================

    elements.append(
        Paragraph(
            "Negotiation History",
            heading_style
        )
    )

    elements.append(
        Spacer(1, 8)
    )

    history_table_data = [
        [
            "Session ID",
            "Scenario",
            "Mode",
            "Rounds",
            "Score",
            "Status"
        ]
    ]

    for item in history_data:

        history_table_data.append([
            item.get("session_id", "-")[:8],
            item.get("scenario", "-"),
            item.get("mode", "-"),
            str(item.get("rounds", "-")),
            str(item.get("negotiation_score", "-")),
            item.get("status", "-")
        ])

    history_table = Table(
        history_table_data,
        colWidths=[85, 125, 75, 50, 55, 95]
    )

    history_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ])
    )

    elements.append(
        history_table
    )

    elements.append(
        Spacer(1, 25)
    )

    # ==========================================
    # Footer
    # ==========================================

    elements.append(
        Paragraph(
            "Generated by Multi-Agent Negotiation Simulator",
            normal_style
        )
    )

    doc.build(elements)